In [24]:
import numpy as np
import pandas as pd
import re   # searching from keywords
from nltk.corpus import stopwords  # articles [a, an, the,in, on, at, with, to, of,he, she, it, they, I, me, my ]
from nltk.stem.porter import PorterStemmer # [ use for root word for perticular work]
from sklearn.feature_extraction.text import TfidfVectorizer # covert in text in feature vectores
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression # for geting fake [0] or not fack [1] binary pridction
from sklearn.metrics import accuracy_score

In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [27]:
# data collection and data preprocessing

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohamadalhasan/a-fake-news-dataset-around-the-syrian-war")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'a-fake-news-dataset-around-the-syrian-war' dataset.
Path to dataset files: /kaggle/input/a-fake-news-dataset-around-the-syrian-war

In [32]:
import pandas as pd

news_dataset = pd.read_csv(
    '/root/.cache/kagglehub/datasets/mohamadalhasan/a-fake-news-dataset-around-the-syrian-war/versions/1/FA-KES-Dataset.csv',
    encoding='latin1'
)

print(news_dataset.head())

      unit_id                                      article_title  \
0  1914947530  Syria attack symptoms consistent with nerve ag...
1  1914947532  Homs governor says U.S. attack caused deaths b...
2  1914947533    Death toll from Aleppo bomb attack at least 112
3  1914947534        Aleppo bomb blast kills six Syrian state TV
4  1914947535  29 Syria Rebels Dead in Fighting for Key Alepp...

                                     article_content source       date  \
0  Wed 05 Apr 2017 Syria attack symptoms consiste...    nna   4/5/2017
1  Fri 07 Apr 2017 at 0914 Homs governor says U.S...    nna   4/7/2017
2  Sun 16 Apr 2017 Death toll from Aleppo bomb at...    nna  4/16/2017
3  Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...    nna  4/19/2017
4  Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...    nna  7/10/2016

  location  labels
0    idlib       0
1     homs       0
2   aleppo       0
3   aleppo       0
4   aleppo       0

,unit_id,article_title,article_content,date,location,labels
source,,,,,,
ahram,286653385898,10 dead after strikes on rebel-held hospitals ...,10 dead after strikes on rebel-held hospitals ...,4/27/20174/19/20174/16/20174/16/20174/15/20174...,idlibaleppoaleppoaleppoaleppoaleppodamascusraq...,74
alalam,176624611613,Bomb blast kills 60 in Damascus suburbCar bomb...,Fri Sep 27 2013 Bomb blast kills 60 in Damascu...,9/27/20132/2/20118/31/20133/15/20128/1/20138/2...,damascusdamascusdamascuslattakiahomsraqqadeir ...,49
alaraby,161448613484,Syrian regime steps up aerial assault on Douma...,12 February 2015 Casualties mount in the Easte...,2/12/20152/12/20152/23/20157/6/20157/7/20157/8...,damascusdamascusidlibraqqaaleppoaleppoidlibale...,48
arabiya,42382542995,Family of six die in east Aleppo chlorine gas ...,Tuesday 22 November 2016 A photo apparently sh...,11/22/201610/7/20175/18/20178/25/20134/6/20171...,aleppoaleppohamadamascusidlibaleppodamascusdam...,10
asharqalawsat,21099650374,Chemical Massacre in Idlib Defies the WorldBus...,April 5 2017 by Youssef Diab Paula Astih and N...,4/5/20174/18/20174/19/20174/4/20173/25/20178/3...,idlibaleppoaleppoidlibhamaidlibaleppoaleppodam...,7
dailysabah,142301073184,Syrian army advances near AleppoMonitor 10 of ...,Published February 18 2015 The Syrian army bac...,2/18/20152/23/20152/23/20157/5/20157/20/20157/...,aleppoaleppolattakiaraqqalattakiaaleppoidlibid...,40
etilaf,88618038589,135 Civilians Killed in Escalating Bombardment...,Wednesday 07 December 2016 135 Civilians Kille...,12/7/20164/23/20167/22/20157/31/201411/21/2014...,idlibdamascusaleppoaleppoaleppodeir ezzoridlib...,20
jordantimes,53873625469,Israeli attack on Syria military camp kills th...,Last updated at Apr 232017 An Israeli attack o...,4/13/20174/13/20174/14/20174/15/20178/19/20168...,quneitraalepporaqqaidlibaleppoaleppoidlibalepp...,20
manar,206144479385,16 Civilians Dead in Coalition Strikes near Ra...,May 24 2017 16 Civilians Dead in Coalition Str...,5/24/20175/30/20175/18/20174/19/20174/10/20174...,raqqadeir ezzorhamaaleppoidlibidlibhomsidlibda...,54
nna,24921649578,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,4/5/20174/7/20174/16/20174/19/20177/10/20167/5...,idlibhomsaleppoaleppoaleppohasakehraqqalattaki...,3
reuters,50088459810,Death toll in Syrian bombing raid on Aleppo ri...,December 16 2013 Death toll in Syrian bombing ...,12/16/20148/17/20138/17/20137/30/20148/21/2013...,aleppodamascusdamascusaleppodamascushomshomsda...,12
sana,107882827242,8 persons killed 58 others injured in terroris...,8 persons killed 58 others injured in terroris...,10/6/201611/21/20169/6/201611/8/20169/4/201610...,alepporaqqaaleppodeir ezzoraleppoaleppoaleppoa...,27
sputnik,104171253850,Syria Accuses Rebels of Using Chemical Weapons...,24.08.2013 Syrian state media accused rebels o...,8/24/20138/21/201312/26/201411/26/201410/18/20...,damascusdamascushasakehaleppohasakehhomsidlibl...,37
tass,9620291107,Jabhat al-Nusra terrorists execute 40 gunmen t...,August 12 2016 Terrorists executed militants a...,8/15/20168/10/20168/7/20168/15/20134/16/2017,aleppoaleppohomsdamascusraqqa,2
trt,80732578568,US jets killed at least 15 civilians in SyriaF...,29 Jul 2016 The US-led coalition strikes came ...,7/29/20167/27/20167/21/20167/12/20167/10/20168...,aleppohasakehaleppoaleppohomsidlibaleppoidlibi...,23

In [34]:
# here 1 - real news and 0 - fake news

In [35]:
# check the number of missing values in the dataset

news_dataset.isnull().sum()

unit_id            0
article_title      0
article_content    0
source             0
date               0
location           0
labels             0
dtype: int64

In [135]:
# merging the author name and title

news_dataset['content'] =  news_dataset['source']+' : ' + news_dataset['article_title']

In [136]:
print(news_dataset['content'])

0      nna : Syria attack symptoms consistent with ne...
1      nna : Homs governor says U.S. attack caused de...
2      nna : Death toll from Aleppo bomb attack at le...
3      nna : Aleppo bomb blast kills six Syrian state TV
4      nna : 29 Syria Rebels Dead in Fighting for Key...
                             ...
799    manar : Turkish Bombardment Kills 20 Civilians...
800    manar : Martyrs as Terrorists Shell Aleppos Sa...
801    manar : Chemical Attack Kills Five Syrians in ...
802    manar : 5 Killed as Russian Military Chopper S...
803    manar : Syrian Army Kills 48 ISIL Terrorists i...
Name: content, Length: 804, dtype: object

In [137]:
x = news_dataset.drop(columns='labels', axis=1)
y = news_dataset['labels']

In [138]:
print(x)
print(y)

        unit_id                                      article_title  \
0    1914947530  Syria attack symptoms consistent with nerve ag...
1    1914947532  Homs governor says U.S. attack caused deaths b...
2    1914947533    Death toll from Aleppo bomb attack at least 112
3    1914947534        Aleppo bomb blast kills six Syrian state TV
4    1914947535  29 Syria Rebels Dead in Fighting for Key Alepp...
..          ...                                                ...
799  1965511221    Turkish Bombardment Kills 20 Civilians in Syria
800  1965511222    Martyrs as Terrorists Shell Aleppos Salah Eddin
801  1965511224  Chemical Attack Kills Five Syrians in Aleppo SANA
802  1965511226  5 Killed as Russian Military Chopper Shot down...
803  1965511231  Syrian Army Kills 48 ISIL Terrorists in Deir E...

                                       article_content source       date  \
0    Wed 05 Apr 2017 Syria attack symptoms consiste...    nna   4/5/2017
1    Fri 07 Apr 2017 at 0914 Homs governor says U.S...    nna   4/7/2017
2    Sun 16 Apr 2017 Death toll from Aleppo bomb at...    nna  4/16/2017
3    Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...    nna  4/19/2017
4    Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...    nna  7/10/2016
..                                                 ...    ...        ...
799  28-08-2016 Turkish Bombardment Kills 20 Civili...  manar  8/28/2016
800  17-08-2016 Martyrs as Terrorists Shell Aleppos...  manar   8/1/2016
801  03-08-2016 Chemical Attack Kills Five Syrians ...  manar   8/3/2016
802  01-08-2016 5 Killed as Russian Military Choppe...  manar   8/1/2016
803  April 6 2017 Syrian Army Kills 48 ISIL Terrori...  manar   4/4/2017

       location                                            content
0         idlib  nna : Syria attack symptoms consistent with ne...
1          homs  nna : Homs governor says U.S. attack caused de...
2        aleppo  nna : Death toll from Aleppo bomb attack at le...
3        aleppo  nna : Aleppo bomb blast kills six Syrian state TV
4        aleppo  nna : 29 Syria Rebels Dead in Fighting for Key...
..          ...                                                ...
799      aleppo  manar : Turkish Bombardment Kills 20 Civilians...
800      aleppo  manar : Martyrs as Terrorists Shell Aleppos Sa...
801      aleppo  manar : Chemical Attack Kills Five Syrians in ...
802       idlib  manar : 5 Killed as Russian Military Chopper S...
803  deir ezzor  manar : Syrian Army Kills 48 ISIL Terrorists i...

[804 rows x 7 columns]
0      0
1      0
2      0
3      0
4      0
      ..
799    1
800    1
801    0
802    1
803    1
Name: labels, Length: 804, dtype: int64

stemming : stemming is process of reducing a word to it's root word

 ex. actor, actoress, acting --> act

In [139]:
port_stem = PorterStemmer()

In [140]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content) # a set where small and capital [ A-Z ]
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [141]:
news_dataset['content'] = news_dataset['content'].apply(stemming)

In [142]:
news_dataset['content']

0        nna syria attack symptom consist nerv agent use
1      nna hom governor say u attack caus death doesn...
2                nna death toll aleppo bomb attack least
3         nna aleppo bomb blast kill six syrian state tv
4             nna syria rebel dead fight key aleppo road
                             ...
799            manar turkish bombard kill civilian syria
800      manar martyr terrorist shell aleppo salah eddin
801     manar chemic attack kill five syrian aleppo sana
802       manar kill russian militari chopper shot syria
803     manar syrian armi kill isil terrorist deir ezzor
Name: content, Length: 804, dtype: object

In [143]:
x = news_dataset['content'].values
y = news_dataset['labels'].values

In [144]:
print(x)

['nna syria attack symptom consist nerv agent use'
 'nna hom governor say u attack caus death doesnt see big human loss'
 'nna death toll aleppo bomb attack least'
 'nna aleppo bomb blast kill six syrian state tv'
 'nna syria rebel dead fight key aleppo road'
 'nna suicid bomb kill least northeast syria'
 'nna dead heavi u raid syria stronghold'
 'nna suicid bomber kill assad clan hometown'
 'nna explos rock town damascu' 'nna damascu explos due rocket bomb'
 'alarabi syrian regim step aerial assault douma'
 'alarabi hizballah lead regim offens southern syria'
 'alarabi syrian opposit remain divid'
 'alarabi video show murder syrian activist'
 'alarabi syria nusra front stage deadli suicid bomb aleppo'
 'alarabi regim troop thwart rebel attack syria aleppo'
 'alarabi ahrar al sham leader kill syria'
 'alarabi barrel bomb kill town syria'
 'alarabi rebel advanc north western syria'
 'alarabi isra strike syrian town kill pro regim fighter'
 'alarabi syria armi plane crash rebel held town'
 'alarabi syrian regim reveng attack kill score qalamoun'
 'asharqalawsat chemic massacr idlib defi world'
 'asharqalawsat bu bomb mark end tragic evacu deal syria'
 'asharqalawsat six kill aleppo bomb evacu syrian town resum'
 'asharqalawsat kill suspect ga attack syria idlib'
 'asharqalawsat msf syrian regim use chemic weapon hama'
 'asharqalawsat toxic ga drop syrian town russian helicopt shot'
 'asharqalawsat syrian opposit spark aleppo front reliev north fraction'
 'asharqalawsat dozen kill intern coalit airstrik manbij'
 'asharqalawsat thirti kill syrian strike damascan suburb town'
 'asharqalawsat russian syrian regim use intern ban bomb attack aleppo'
 'asharqalawsat syria kurdish islamist violenc kill al qaeda link fighter'
 'dailysabah syrian armi advanc near aleppo'
 'dailysabah monitor peopl execut forc loyal regim children'
 'dailysabah suicid bomber kill assad clan hometown'
 'dailysabah us led airstrik target isi stronghold raqqa'
 'dailysabah assad regim launch oper latakia region attack syrian turkmen villag'
 'dailysabah assad regim kill civilian aleppo monitor'
 'dailysabah russian airstrik hit syrian opposit forc'
 'dailysabah syrian warplan crash market northwest town ariha near turkish border kill wound dozen'
 'dailysabah suicid bomb attack syria idlib mosqu kill senior nusra front leader'
 'dailysabah civilian kill syria hasakeh motorbik bomber attack'
 'dailysabah medic among least dead regim shell opposit held syrian town'
 'dailysabah assad regim airstrik kill civilian syria aleppo'
 'dailysabah coalit airstrik kill civilian daesh held villag syria manbij'
 'dailysabah assad regim surround aleppo opposit group resist despit intens raid'
 'trt us jet kill least civilian syria'
 'trt fatal expect increas suicid blast syria'
 'trt us led air strike syria kill dozen civilian'
 'trt syrian opposit advanc key aleppo district'
 'trt two russian pilot kill syria daesh down chopper'
 'trt least dead bomb hit refuge camp syria idlib'
 'trt ga attack hit rebel held area aleppo report'
 'trt syrian regim forc drop vacuum bomb idlib'
 'trt chemic attack idlib draw intern condemn'
 'trt regim air strike kill syria rebel held region'
 'trt air strike kill least northwestern syria'
 'trt multipl daesh suicid bomber attack refuge camp syria'
 'trt air strike syria kill eight white helmet activist'
 'trt air strike hit hospit kill peopl idlib'
 'trt deadli bomb blast hit syria aleppo'
 'trt least kill bomb hit bu convoy syria'
 'alarabi suicid bomber kill syria hasakah'
 'alarabi bomb continu fall syria despit regim truce'
 'alarabi syrian rebel fighter kill suicid bomb attack'
 'alarabi score syrian rebel kill key aleppo road'
 'alarabi us led coalit raid kill score civilian syria'
 'alarabi dozen kill bombard rebel held aleppo'
 'alarabi seven children kill syria rebel held aleppo'
 'alarabi syria airstrik destroy idlib msf hospit leav dead'
 'alarabi dozen kill russian air raid held raqqa'
 'alarabi four kill suspect ga attack aleppo'
 'alarabi three women kill attend funer syria madaya'
 'alarabi violenc rage syria dozen kill'
 'alarabi civilian kill syria aleppo'
 'alarabi syrian regim bomb kurdish fighter second day'
 'alarabi barrel bomb attack kill children syria aleppo'
 'alarabi children kill syria hom napalm mortar round'
 'alarabi kill regim strike besieg hom neighbourhood'
 'alarabi dozen kill hospit damag strike hit northwest syria'
 'alarabi score kill ga attack rebel held syria town'
 'alarabi syrian regim airstrik kill civilian near damascu'
 'alarabi shell rebel bastion near syrian capit kill'
 'alarabi syrian airbas struck us missil what damag'
 'alarabi strike syria idlib kill includ five children'
 'alarabi sarin nerv ga use syria british scientist'
 'alarabi syria rebel battl break aleppo sieg'
 'alarabi syrian children kill west aleppo school attack'
 'alarabi idlib bomb deadliest school attack syria war'
 'alarabi student among score dead raid hit syria school'
 'alarabi two dead twenti injur syrian regim chlorin attack'
 'alarabi heavi syrian regim bomb idlib kill civilian'
 'alarabi russia say belgian strike kill six aleppo region'
 'alarabi hour bombard aleppo kill'
 'alarabi dozen kill car bomb attack syrian rebel'
 'alarabi airstrik continu rain east aleppo'
 'alarabi russia launch new crippl air raid aleppo'
 'alarabi eleven kill syrian regim control area aleppo'
 'alarabi air raid kill syrian held villag'
 'alarabi suicid attack syria wed kill'
 'alarabi suicid attack kurdish wed syria kill'
 'alarabi two kill qatar red crescent syria clinic bomb'
 'alarabi syrian refuge camp hit missil bomb'
 'alarabi aleppo score kill airstrik target un aid convoy'
 'alarabi first civilian kill aleppo sinc start ceasefir'
 'alarabi syrian children kill missil attack school'
 'alarabi five dead syria airstrik ahead plan ceasefir'
 'alarabi syria regim kill civilian hama airstrik'
 'alarabi hundr dead fresh airstrik hit syria aleppo'
 'alarabi deadli aleppo convoy attack threaten aid distribut syria'
 'alarabi four medic kill strike clinic near aleppo'
 'alarabi syrian civil defenc us russia regim attack aid convoy'
 'alarabi syrian regim repel rebel offens near aleppo kill'
 'alarabi syrian regim offens northern aleppo leav dead'
 'alarabi unicef confirm children among deir ez zor dead'
 'alarabi score civilian kill airstrik raqqa'
 'alarabi heavi regim loss islam state raqqa counteroffens'
 'alarabi three children kill regim airstrik hom'
 'alarabi four hizballah member kill fight syria'
 'alarabi dozen dead suspect russian strike idlib marketplac'
 'alarabi airstrik syria kill dozen start ramadan'
 'alarabi dozen syrian regim air raid rebel held aleppo'
 'alarabi syrian regim airstrik kill dozen around aleppo'
 'alarabi airstrik kill civilian syria safe zone monitor'
 'alarabi us led strike kill civilian syria raqqa'
 'alarabi deadli twin bomb hit damascu polic station'
 'alarabi russian airstrik kill score flee civilian deir az zor'
 'alarabi syrian regim airstrik idlib market kill children'
 'alarabi tripl suicid attack near damascu polic hq ministri'
 'alarabi rebel shell kill four civilian damascu monitor'
 'alarabi three white helmet worker six children kill syria air'
 'alarabi civilian kill relentless regim bomb besieg damascu'
 'alarabi syrian regim airstrik target besieg eastern ghouta deir az zor'
 'alarabi russian strike kill civilian syria deir az zour'
 'ahram dead strike rebel held hospit syria'
 'ahram aleppo bomb blast kill six syrian state'
 'ahram dozen children dead syria evacue bomb'
 'ahram death toll aleppo bu convoy bomb attack least observatori'
 'ahram bomb syrian bu convoy kill wound dozen outsid aleppo'
 'ahram death toll bomb attack syria evacue hit monitor'
 'ahram dead clash islamist milit near damascu monitor'
 'ahram us back syrian fighter press gunmen north'
 'ahram strike kill includ children syria idlib monitor'
 'ahram one dead raid syria chemic attack town monitor'
 'ahram dead suspect syria chemic attack new toll'
 'ahram shell rebel bastion near syria capit kill monitor'
 'ahram suspect ga attack syria rebel held idlib kill least observatori'
 'ahram barrel bomb attack kill children syria aleppo monitor'
 'ahram syria regim pound kurdish posit second day'
 'ahram syrian rebel kill group suicid blast'
 'ahram warplan pound syria idlib battl rage aleppo'
 'ahram rebel fire syria aleppo kill state media'
 'ahram air raid kill near syria hospit monitor'
 'ahram barrel bomb kill least civilian syria aleppo monitor'
 'ahram civilian dead air strike syria rebel town monitor'
 'ahram syria regim bomb kill rebel held aleppo monitor'
 'ahram doubl bomb attack kill syrian kurdish citi state tv'
 'ahram syrian state tv say kill car bomb northern syria'
 'ahram aleppo rebel tunnel blast kill regim forc monitor'
 'ahram us led strike kill civilian syria monitor'
 'ahram coalit raid kill civilian stronghold syria monitor'
 'ahram air raid kill civilian syria aleppo monitor'
 'ahram air raid kill civilian east syria monitor'
 'ahram air strike kill rebel held area syria aleppo monitor'
 'ahram air strike kill includ children syria idlib monitor'
 'ahram coalit air strike turkish armi kill group milit report'
 'ahram rocket attack kill least syria aleppo'
 'ahram motorbik bomber kill outsid bakeri syria hasakeh'
 'ahram kill syria armi shell rebel town monitor'
 'ahram medic among dead syria armi repris slain pilot'
 'ahram syria air raid kill civilian monitor'
 'ahram dead attack kurd held syria town monitor'
 'ahram syria rebel rocket kill five children'
 'ahram turkish air strike kill fighter syria monitor'
 'ahram civilian dead syrian raid held villag monitor'
 'ahram missil kill civilian syria aleppo monitor'
 'ahram barrel bomb kill civilian town syria'
 'ahram civilian kill regim air raid northern syria'
 'ahram huge regim bomb kill held syria town monitor'
 'ahram bomb rocket kill civilian syria aleppo monitor'
 'ahram dead new islamist allianc attack syria aleppo monitor'
 'ahram air strike syria kill least islam state fighter monitor'
 'ahram syria regim air strike kill near damascu monitor'
 'ahram syrian air strike kill peopl rebel rocket attack monitor'
 'ahram syria strike kill rebel fire damascu monitor'
 'ahram syria air strike kill monitor'
 'ahram seven dead wound central damascu blast monitor'
 'ahram syria fight kill islam state fighter monitor'
 'ahram suicid bomber kill assad clan hometown'
 'ahram syria forc execut children alleg rebel monitor'
 'ahram jihadist kill clash syria kurd monitor'
 'ahram suicid bomber kill six syria restaur report'
 'ahram dead al qaeda attack syria kurd town'
 'ahram dead air raid syria latakia provinc ngo'
 'ahram syrian armi kill rebel east damascu monitor group'
 'ahram bomb kill damascu suburb state tv'
 'ahram least kill syrian weapon depot blast'
 'ahram syria regim raid kill camp displac ngo'
 'ahram attack syria oil field kill monitor'
 'ahram syria air strike kill children women aleppo monitor'
 'ahram syrian troop kill clash monitor'
 'ahram syria regim bomb kill includ children'
 'ahram twin blast kill kurdish fighter syria monitor'
 'ahram us led strike syria kill jihadist overnight monitor'
 'ahram us led raid syria kill jihadist civilian'
 'ahram us strike kill qaeda fighter syria monitor'
 'ahram us led strike hit qaeda syria well monitor'
 'ahram us led strike syria kill jihadist monitor'
 'ahram syria air strike kill includ children monitor'
 'ahram jihadist kill fight syria kurd monitor'
 'ahram syria air strike kill dozen rebel town monitor'
 'ahram worker dig dead syria regim strike aleppo'
 'ahram updat regim air raid kill near syria capit new toll'
 'ahram american among jihadist kill syria raid ngo'
 'ahram syria armi kill rebel daraa provinc ambush ngo'
 'ahram syria bomb jihadist posit raqa second day'
 'ahram kill syria daraa aleppo ngo'
 'ahram air raid kill jihadist syria raqa ngo'
 'ahram syria troop kill least jihadist near lebanon monitor'
 'ahram syria air strike jihadist camp kill new toll'
 'ahram syria troop kill jihadist advanc monitor'
 'ahram syria air raid kill islam state milit monitor'
 'ahram russian strike kill civilian syria deir ezzor monitor'
 'ahram car bomb kill eastern syria state media'
 'ahram least kill air strike syrian market town observatori'
 'ahram air raid kill civilian north syria town monitor'
 'ahram bodi civilian found syrian town taken group'
 'ahram rebel shell kill four civilian damascu monitor'
 'ahram least dead syria market air strike monitor'
 'ahram russia strike kill group fighter foreign mercenari syria'
 'ahram monitor kill missil strike eastern syria citi'
 'ahram us led strike kill civilian syria raqa monitor'
 'ahram least kill north syria aleppo monitor'
 'ahram russia regim strike kill east syria monitor'
 'ahram civilian kill raid syria group bastion raqa monitor'
 'ahram syria rebel kill aleppo assault captur villag monitor'
 'ahram air strike syria idlib kill monitor'
 'ahram civilian dead air strike market east syria monitor'
 'ahram syria regim raid aleppo kill civilian monitor'
 'ahram updat syria regim strike near aleppo civil defenc'
 'ahram suicid bomber kill one syria regim stronghold state tv'
 'ahram children among dead syria regim bomb civil defenc'
 'ahram opposit minist among dead syria car bomb rebel'
 'ahram civilian kill syria aid convoy attack red cross'
 'ahram russia say syrian troop kill us led strike'
 'ahram kill raid syria idlib monitor'
 'ahram new strike kill least civilian syria aleppo monitor'
 'ahram syrian armi say rebel bombard aleppo kill three day'
 'ahram dozen civilian dead rebel assault aleppo'
 'ahram rebel aleppo attack putin cautiou new russian raid'
 'ahram rebel fire kill aleppo schoolchildren state media'
 'ahram syria monitor say air strike kill school rebel held idlib'
 'ahram group group land mine kill wound dozen syrian town'
 'ahram dead heavi bombard syria idlib monitor'
 'ahram air raid kill least civilian syria aleppo monitor'
 'ahram turkish militari say group milit kill northern syria'
 'ahram blast syria turkey border kill rebel monitor'
 'ahram suicid attack syria wed kill medic sourc'
 'ahram isil crucifi men syria aleppo ngo'
 'ahram least syrian soldier kill isra raid ngo'
 'ahram jihadist execut three syria rebel offic monitor'
 'ahram car bomb kill least syria hama state media region world ahram onlin'
 'ahram syria air raid displac person camp kill ngo region world ahram onlin'
 'ahram dead syria barrel bomb attack aleppo'
 'ahram syria rebel infight kill fighter day region world ahram onlin'
 'ahram car bomb syria hom kill governor region world ahram onlin'
 'ahram kill syria rebel shell assad elect ralli monitor region world ahram onlin'
 'ahram syrian armi missil kill includ kid region world ahram onlin'
 'ahram bomb syria idlib kill govern fighter monitor group region world ahram onlin'
 'ahram children among dead syria car bomb state media region world ahram onlin'
 'ahram car bomb rocket fire kill syria hom governor region world ahram onlin'
 'ahram mortar fire damascu kill wound state media region world ahram onlin'
 'ahram dead rebel fire regim part aleppo ngo region world ahram onlin'
 'ahram dead two day clash syria daraa monitor region world ahram onlin'
 'ahram air raid kill syria market monitor region world ahram onlin'
 'ahram air strike kill dozen syria aleppo monitor group region world ahram onlin'
 'ahram twin car bomb kill syria hom state media region world ahram onlin'
 'ahram rebel dead syria prematur car bomb blast ngo region world ahram onlin'
 'ahram mortar fire kill two damascu opera hous state media region world ahram onlin'
 'ahram syria rebel jihadist kill ngo region world ahram onlin'
 'ahram car bomb kill six syria hom ngo region world ahram onlin'
 'ahram car bomb blast kill syria hom ngo region world ahram onlin'
 'ahram five dead blast secur hq central syria ngo region world ahram onlin'
 'jordantim isra attack syria militari camp kill three jordan time'
 'jordantim dozen dead car bomb hit syria evacue jordan time'
 'jordantim strike kill near syria daesh held raqqa monitor jordan time'
 'jordantim outrag syria chemic attack kill dozen rebel held town jordan time'
 'jordantim five dead russian militari helicopt down syria jordan time'
 'jordantim dozen dead warplan pound rebel held north syria jordan time'
 'jordantim dozen dead warplan pound rebel held north syria jordan time'
 'jordantim least kill north syria aleppo monitor jordan time'
 'jordantim massiv daesh bomb attack kill syrian kurdish citi jordan time'
 'jordantim syria regim advanc rebel aleppo monitor jordan time'
 'jordantim civilian kill regim air raid northern syria jordan time'
 'jordantim barrel bomb kill civilian daesh town syria jordan time'
 'jordantim syria regim air strike kill least monitor jordan time'
 'jordantim syria air strike kill least monitor jordan time'
 'jordantim syria regim air strike kill near damascu monitor jordan time'
 'jordantim massiv daesh bomb attack kill syrian kurdish citi jordan time'
 'jordantim least kill north syria aleppo monitor jordan time'
 'jordantim syria rebel kill aleppo assault captur villag monitor jordan time'
 'jordantim raid syria market kill hundr flee daesh bastion jordan time'
 'jordantim dead daesh counterattack syria regim forc jordan time'
 'jordantim syrian russian aircraft step bomb aleppo citi monitor jordan time'
 'jordantim syria air strike kill mostli children outsid school jordan time'
 'jordantim syrian govern push damascu rebel enclav kill least jordan time'
 'jordantim air strike kill syria truce zone monitor jordan time'
 'jordantim syria regim bombard kill schoolchildren besieg enclav jordan time'
 'jordantim russian strike kill flee civilian east syria monitor jordan time'
 'jordantim us led strike kill civilian syria raqqa monitor jordan time'
 'jordantim russia say kill extremist mercenari syria claim shishani death jordan time'
 'nna nation news agenc damascu explos due rocket bomb'
 'nna nation news agenc blast syria hom kill children'
 'nna nation news agenc coalit raid kill isil fighter'
 'trt least kill bomb hit bu convoy syria'
 'trt us led air strike syria kill dozen civilian'
 'trt two russian pilot kill syria daesh down chopper'
 'trt us jet kill least civilian syria' 'trt russian strike kill aleppo'
 'trt syrian russian air strike kill civilian idlib'
 'trt syrian russian air strike kill citi ashara'
 'trt suicid attack near shia shrine kill syrian observatori'
 'trt russian syrian strike kill civilian'
 'trt us russia broker syria truce end'
 'trt air strike syria kill least peopl'
 'trt string bomb blast kill least syria'
 'trt heavi air strike hit opposit held part aleppo'
 'trt unicef say schoolchildren six teacher kill syria raid'
 'trt russian syrian regim strike kill aleppo'
 'trt car bomb syria kill least near turkish border'
 'trt russian jet resum airstrik aleppo'
 'trt suicid bomb kill syria turkey border'
 'trt suicid bomber target syrian wed kill'
 'trt car bomb attack kill least syria war monitor say'
 'trt air strike kill dozen insid syria de escal zone'
 'trt least seven children die regim shell rebel held area syria'
 'trt least civilian kill russian regim air strike syria'
 'trt russia air strike kill least civilian syria monitor'
 'trt least dead suicid bomb hit damascu'
 'trt unidentifi air strike kill least eight hezbollah fighter syria'
 'dailysabah least kill dozen injur twin bomb target syria qamishli near turkish border daili sabah'
 'dailysabah air strike syrian hospit kill monitor group say daili sabah'
 'dailysabah civilian kill russian air strike syria aleppo daili sabah'
 'dailysabah russian airstrik target civilian syria idlib kill daili sabah'
 'dailysabah daesh russia syrian regim target opposit daili sabah'
 'dailysabah syrian warplan pound idlib leav dead daili sabah'
 'dailysabah assad regim helicopt kill peopl barrel bomb aleppo daili sabah'

In [145]:
print(y)

[0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 1 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 1 1 1 0 0 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 0 0
 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 0
 1 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 1 1 0 1 0 1
 0 0 0 0 0 1 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1
 0 1 1 0 0 1 1 1 1 0 0 0 0 1 1 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0
 1 0 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1
 0 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1
 1 0 1 0 1 1 0 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 1
 1 1 0 1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 0
 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 1 0
 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0
 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 1
 1 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 0 1
 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0 0 0
 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 1 1 0 0 0 1 1
 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 1 1 0 0 1 1 1 1 1 1 1 1 0
 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0
 0 1 1 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1]

In [146]:
# coverting sentences to meaning full numbers - here we use vectors

vectorizer = TfidfVectorizer()  # convert raw text documents into a matrix of numerical features.
vectorizer.fit(x)

x = vectorizer.transform(x)

In [147]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7116 stored elements and shape (804, 775)>
  Coords	Values
  (0, 21)	0.4398385037739128
  (0, 71)	0.154270763028172
  (0, 156)	0.4398385037739128
  (0, 465)	0.4143530883600743
  (0, 471)	0.31752877227058074
  (0, 674)	0.4398385037739128
  (0, 675)	0.1123974588039333
  (0, 737)	0.33268695746858934
  (1, 71)	0.12184316409612725
  (1, 95)	0.34738477945645097
  (1, 122)	0.3272563792892771
  (1, 188)	0.24114602484679362
  (1, 211)	0.34738477945645097
  (1, 301)	0.30189759411838357
  (1, 324)	0.20673629748416938
  (1, 334)	0.34738477945645097
  (1, 407)	0.30189759411838357
  (1, 471)	0.2507844619783276
  (1, 603)	0.22200068141769194
  (1, 612)	0.34738477945645097
  (2, 36)	0.21999407466746793
  (2, 71)	0.23968501507821843
  (2, 99)	0.2929163001914418
  (2, 188)	0.47437284668556384
  (2, 394)	0.3389939588680877
  :	:
  (800, 622)	0.34302181140418664
  (800, 692)	0.2062183140289721
  (801, 36)	0.24495050157124273
  (801, 71)	0.26687520903126616
  (801, 130)	0.45606413404262736
  (801, 270)	0.5492975843885451
  (801, 381)	0.15174570674440918
  (801, 413)	0.32917973998152034
  (801, 599)	0.39474553415539776
  (801, 676)	0.26803814382300173
  (802, 136)	0.5350119613527945
  (802, 381)	0.11843037923443349
  (802, 413)	0.25690928777291416
  (802, 435)	0.4761906092906068
  (802, 595)	0.31258727036978734
  (802, 627)	0.5350119613527945
  (802, 675)	0.15174968723354954
  (803, 60)	0.37289239331415397
  (803, 195)	0.4287766760420207
  (803, 253)	0.48679880952424
  (803, 358)	0.4287766760420207
  (803, 381)	0.14469626253434315
  (803, 413)	0.31388748386522486
  (803, 676)	0.2555862598021082
  (803, 692)	0.26738101858706614

In [148]:
# here now we fit this data to machine learning model

# here split our x and y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, stratify=y, random_state=2)

# stratify = While splitting, keep the same proportion of classes.
# random_state = Shuffle in a special fixed way so I get the same result every time.
# Today's split → Different
# Tomorrow's split → Different

In [149]:
model = LogisticRegression()

In [150]:
# training the model : Logistic Regression model [getting binory ]

model.fit(x_train, y_train)

LogisticRegression()

In [151]:
# accuracy score

x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [152]:
print('the accuracy of :',training_data_accuracy*100)

the accuracy of : 78.42323651452283

In [153]:
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [154]:
print('the accuracy of :',testing_data_accuracy*100)

the accuracy of : 58.0246913580247

In [155]:
# making predictive system

x_new = x_test[0]

prediction = model.predict(x_new)

print(prediction)

if(prediction[0]==0):
  print('the news is real')
else:
  print('the news is fake')

[1]
the news is fake

In [158]:
news_dataset['source'].unique()

array(['nna', 'alaraby', 'asharqalawsat', 'dailysabah', 'trt', 'ahram',
       'jordantimes', 'tass', 'sana', 'etilaf', 'manar', 'arabiya',
       'reuters', 'alalam', 'sputnik'], dtype=object)

In [132]:
# Install widgets (run once)
 !pip install -q ipywidgets

In [156]:
# ===============================
# GUI FOR FAKE NEWS DETECTION
# ===============================



import ipywidgets as widgets
from IPython.display import display, HTML

# -------------------------------
# Prediction Function
# -------------------------------

def predict_news(source, headline):

    # Same format used during training
    content = source + " : " + headline

    # Preprocess
    processed = stemming(content)

    # Convert to TF-IDF
    vector = vectorizer.transform([processed])

    # Prediction
    prediction = model.predict(vector)

    return prediction[0]


# -------------------------------
# Source Input
# -------------------------------

source_box = widgets.Text(
    placeholder='Example: ndtv',
    description='Source:',
    layout=widgets.Layout(width='600px')
)

# -------------------------------
# Headline Input
# -------------------------------

headline_box = widgets.Textarea(
    placeholder='Paste news headline here...',
    description='Headline:',
    layout=widgets.Layout(width='800px', height='120px')
)

# -------------------------------
# Predict Button
# -------------------------------

predict_button = widgets.Button(
    description='Check News',
    button_style='success',
    icon='search'
)

# -------------------------------
# Output Area
# -------------------------------

output = widgets.Output()


# -------------------------------
# Button Function
# -------------------------------

def check_news(button):

    output.clear_output()

    source = source_box.value.strip()
    headline = headline_box.value.strip()

    with output:

        if source == "" or headline == "":
            display(HTML(
                "<h3 style='color:red;'>Please enter Source and Headline.</h3>"
            ))
            return


        result = predict_news(source, headline)


        if result == 0:
            display(HTML(
                """
                <h2 style='color:green;'>
                🟢 REAL NEWS
                </h2>
                """
            ))
        else:
            display(HTML(
                """
                <h2 style='color:red;'>
                🔴 FAKE NEWS
                </h2>
                """
            ))


# Connect button
predict_button.on_click(check_news)


# -------------------------------
# Display GUI
# -------------------------------

display(HTML("<h2>Fake News Detection System</h2>"))

display(source_box)
display(headline_box)
display(predict_button)
display(output)

Text(value='', description='Source:', layout=Layout(width='600px'), placeholder='Example: ndtv')

Textarea(value='', description='Headline:', layout=Layout(height='120px', width='800px'), placeholder='Paste n…

Button(button_style='success', description='Check News', icon='search', style=ButtonStyle())

Output()